FROM ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive
WORKDIR /
RUN echo "deb [trusted=yes] https://repo.iovisor.org/apt/xenial xenial-nightly main" | tee /etc/apt/sources.list.d/iovisor.list
RUN apt-get update && apt-get install -y zip bison build-essential cmake flex git libedit-dev \
    libllvm14 llvm-14-dev libclang-14-dev python3 python3-pip python-is-python3 build-essential python3-dev zlib1g-dev libelf-dev libfl-dev python3-setuptools \
    liblzma-dev libdebuginfod-dev arping netperf iperf bpfcc-tools \
    docker.io \ 
    && rm -rf /var/lib/apt/lists/*
COPY . /
RUN pip install -r requirements.txt  -i https://pypi.tuna.tsinghua.edu.cn/simple 
CMD ["python3", "/main.py"]
